# Generated by Django 6.0.7 on 2026-10-02 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_role_alter_user_role_userrolehistory"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userrolehistory",
            name="unique_current_role_per_user",
        ),
        migrations.RemoveField(
            model_name="userrolehistory",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userrolehistory",
            name="user",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserRoleHistory",
        ),
    ]
